apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: bestbuy
data:
  username: "username"
  hostname: "rabbitmq"
  host: "rabbitmq"
  port: "5672"
  queue-name: "orders"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: bestbuy
data:
  hostname: "mongodb"
  port: "27017"
  database-name: "orderdb"
  collection-name: "orders"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: bestbuy
data:
  ORDER_QUEUE_HOSTNAME: "rabbitmq"
  ORDER_QUEUE_PORT: "5672"
  ORDER_QUEUE_NAME: "orders"
  ORDER_QUEUE_RECONNECT_LIMIT: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: makeline-service-config
  namespace: bestbuy
data:
  ORDER_QUEUE_URI: "amqp://username:password@rabbitmq:5672"
  ORDER_QUEUE_NAME: "orders"
  ORDER_DB_URI: "mongodb://mongodb:27017"
  ORDER_DB_NAME: "orderdb"
  ORDER_DB_COLLECTION_NAME: "orders"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: bestbuy
data:
  PORT: "3002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: store-front-config
  namespace: bestbuy
data:
  VUE_APP_PRODUCT_SERVICE_URL: "http://product-service:3002/"
  VUE_APP_ORDER_SERVICE_URL: "http://order-service:3000/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: store-admin-config
  namespace: bestbuy
data:
  VUE_APP_PRODUCT_SERVICE_URL: "http://product-service:3002/"
  VUE_APP_MAKELINE_SERVICE_URL: "http://makeline-service:3001/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-enabled-plugins
  namespace: bestbuy
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_amqp1_0].
